# env.defaults.sh — portable fleet defaults. COMMITTED (unlike env.sh, which is
# per-machine and generated by install.sh). SOURCE this first, then env.sh on top.
#
# Purpose: make the spawn chain work WITHOUT install.sh having run — a teammate who
# `herdr plugin link`s the nexus-fleet picker and launches it, or a relocated
# NEXUS_TMUX_DIR with no env.sh, still gets a usable agent. Everything here is a
# ${VAR:-default} so a real env.sh (or the caller's env) always wins.
#
# Do NOT put machine-specific absolutes here (tokens, personal gateway IPs, one
# host's checkout path). Those belong in env.sh. This file is the same on every box.

# Fleet install root. The spawn-chain scripts also self-default this; kept here so a
# consumer that sources only env.defaults.sh still has it.
export NEXUS_TMUX_DIR="${NEXUS_TMUX_DIR:-$HOME/.tmux}"

# Fleet substrate: herdr is the DEFAULT backend. The tmux backend is a deprecated,
# flag-selectable fallback — every consumer also self-defaults to herdr, so this is the
# one authoritative declaration, exported so child processes (hooks, agent-send, the
# daemon, node services) inherit it. To roll a box (or one shell) back to tmux, set
# NEXUS_SUBSTRATE=tmux in env.sh (sourced after this) or the process env.
export NEXUS_SUBSTRATE="${NEXUS_SUBSTRATE:-herdr}"

# ── Per-machine path defaults (degrade path only) ────────────────────────────
# Seed these ONLY when there is no env.sh to set them. This file is sourced BEFORE
# env.sh, so assigning them unconditionally here would shadow an env.sh that uses the
# ${VAR:-…} idiom — silently defeating the "env.sh on top always wins" contract above
# (a box whose repos live under, say, ~/work/repos would still get ~/repos → empty
# picker). A teammate who only linked the picker (no install.sh, no env.sh) still gets
# a usable fallback here; the consuming scripts also self-default (${REPO_DIR:-$HOME/repos})
# as a last resort. A box whose repos/checkpoints live elsewhere sets these in env.sh.
if [ ! -f "$NEXUS_TMUX_DIR/env.sh" ]; then
  export REPO_DIR="${REPO_DIR:-$HOME/repos}"
  export CHECKPOINT_DIR="${CHECKPOINT_DIR:-$HOME/vault/Checkpoints}"
fi

# ── Agent bus defaults (safe if the bridge is down — open-claude probes health) ─
export SENDMESSAGE_BUS_ENABLED="${SENDMESSAGE_BUS_ENABLED:-1}"
export SLACK_BUS_ENABLED="${SLACK_BUS_ENABLED:-0}"
export SLACK_A2A_SAMEHOST="${SLACK_A2A_SAMEHOST:-local}"

# ── Agent spawn context (open-claude.sh opening-prompt injection) ────────────
# open-claude.sh assembles a new agent's opening prompt from several context
# blocks. These knobs control which blocks load and how big they are — trim them
# to shrink the context a fresh agent starts with (faster, cheaper spawns).
# Override any of them in env.sh (sourced after this file).
export NEXUS_INJECT_CHECKPOINTS="${NEXUS_INJECT_CHECKPOINTS:-1}"   # recent checkpoint notes for the repo (0 = omit)
export NEXUS_CHECKPOINT_DAYS="${NEXUS_CHECKPOINT_DAYS:-3}"         # how many days of checkpoints to include
export NEXUS_CHECKPOINT_MAX_KB="${NEXUS_CHECKPOINT_MAX_KB:-0}"     # cap the checkpoint block size in KB (0 = unlimited)
export NEXUS_INJECT_MEMORY="${NEXUS_INJECT_MEMORY:-1}"            # 'Prior Knowledge' recall from the memory store (0 = omit)
export NEXUS_MEMORY_MAX_TOKENS="${NEXUS_MEMORY_MAX_TOKENS:-2000}"  # token budget for the memory recall block
export NEXUS_INJECT_CACHE="${NEXUS_INJECT_CACHE:-1}"             # resume-from-interrupted-session cache, <24h (0 = omit)
export NEXUS_INJECT_REGISTRY="${NEXUS_INJECT_REGISTRY:-1}"        # Agent Communication + live peer list (0 = omit)

# ── Conductor run mode (explicit; NEVER encoded in the goal text) ────────────
# dry (default, safe — reporting is LOGGED, not sent) | live (files Jira/MR/Confluence for real).
# conductor-run.sh reads this; conductor.py honors it and exports it to detached/distributed
# missions. A box that should run LIVE missions sets this to 'live' in env.sh (e.g. the personal
# `nexus` box); every other box stays dry so an accidental keystroke never files a real ticket.
# Per-run override: `conductor.py --live` / `--dry-run`.
export CONDUCTOR_RUN_MODE="${CONDUCTOR_RUN_MODE:-dry}"

# ── Anthropic routing (the real degrade fix) ─────────────────────────────────
# Route through a local LiteLLM gateway ONLY when it actually answers, so Langfuse
# gets the trace. When there's no gateway (a teammate's box), leave ANTHROPIC_BASE_URL
# UNSET so claude talks to Anthropic directly — never force a localhost URL that
# isn't listening (that was the one hard break in the degrade path). env.sh may set
# PERSONAL_LITELLM_URL to a non-localhost target (e.g. a LAN tailscale IP); it's
# sourced after this file, so re-run the probe there if it overrides the URL.
PERSONAL_LITELLM_URL="${PERSONAL_LITELLM_URL:-http://localhost:4000}"
if command -v curl >/dev/null 2>&1 && \
   curl -sf -m 0.3 "$PERSONAL_LITELLM_URL/health/liveliness" >/dev/null 2>&1; then
  export ANTHROPIC_BASE_URL="$PERSONAL_LITELLM_URL"
else
  unset ANTHROPIC_BASE_URL
fi

# Model default is intentionally NOT set here — unset means claude uses its own
# current default, which is the right behavior for a fresh install. env.sh pins one.

# ── Secrets backend chain ────────────────────────────────────────────────────
# Ordered resolver (scripts/secrets/secret-get.sh | secret-run.sh): try each backend
# left→right, first non-empty wins; every adapter fail-softs. The public default is `env`
# (a fresh clone with no Doppler resolves purely from the process env / .env). A Doppler
# or AWS box adds fallbacks here or in env.sh, e.g. NEXUS_SECRETS_BACKENDS=env,doppler.
# NOTE: the Doppler-historical launchers (dbmate.sh, boot-notify, slack-bridge unit)
# self-default to env,doppler on their own and don't source this file, so existing boxes
# keep working with NO change here.
export NEXUS_SECRETS_BACKENDS="${NEXUS_SECRETS_BACKENDS:-env}"
export DOPPLER_PROJECT="${DOPPLER_PROJECT:-nexus}"
export DOPPLER_CONFIG="${DOPPLER_CONFIG:-prd}"
export AWS_SM_PREFIX="${AWS_SM_PREFIX:-}"
