# env.defaults.sh — portable fleet defaults. COMMITTED (unlike env.sh, which is
# per-machine and generated by install.sh). SOURCE this first, then env.sh on top.
#
# Purpose: make the spawn chain work WITHOUT install.sh having run — a teammate who
# `herdr plugin link`s the nexus-fleet picker and launches it, or a relocated
# NEXUS_TMUX_DIR with no env.sh, still gets a usable agent. Everything here is a
# ${VAR:-default} so a real env.sh (or the caller's env) always wins.
#
# Do NOT put machine-specific absolutes here (tokens, personal gateway IPs, one
# host's checkout path). Those belong in env.sh. This file is the same on every box.

# Fleet install root. The spawn-chain scripts also self-default this; kept here so a
# consumer that sources only env.defaults.sh still has it.
export NEXUS_TMUX_DIR="${NEXUS_TMUX_DIR:-$HOME/.tmux}"

# Fleet substrate: herdr is the DEFAULT backend. The tmux backend is a deprecated,
# flag-selectable fallback — every consumer also self-defaults to herdr, so this is the
# one authoritative declaration, exported so child processes (hooks, agent-send, the
# daemon, node services) inherit it. To roll a box (or one shell) back to tmux, set
# NEXUS_SUBSTRATE=tmux in env.sh (sourced after this) or the process env.
export NEXUS_SUBSTRATE="${NEXUS_SUBSTRATE:-herdr}"

# ── OS-aware path defaults ───────────────────────────────────────────────────
# The mac fleet lives under ~/repos; the Linux personal box uses ~/repos.
# The scripts' inline `${REPO_DIR:-$HOME/repos}` fallback is wrong on mac (empty
# picker), so pick the right default by platform here.
case "$OSTYPE" in
  darwin*) _NX_REPO_DEFAULT="$HOME/repos" ;;
  *)       _NX_REPO_DEFAULT="$HOME/repos" ;;
esac
export REPO_DIR="${REPO_DIR:-$_NX_REPO_DEFAULT}"
export CHECKPOINT_DIR="${CHECKPOINT_DIR:-$HOME/vault/Checkpoints}"
unset _NX_REPO_DEFAULT

# ── Agent bus defaults (safe if the bridge is down — open-claude probes health) ─
export SENDMESSAGE_BUS_ENABLED="${SENDMESSAGE_BUS_ENABLED:-1}"
export SLACK_BUS_ENABLED="${SLACK_BUS_ENABLED:-0}"
export SLACK_A2A_SAMEHOST="${SLACK_A2A_SAMEHOST:-local}"

# ── Anthropic routing (the real degrade fix) ─────────────────────────────────
# Route through a local LiteLLM gateway ONLY when it actually answers, so Langfuse
# gets the trace. When there's no gateway (a teammate's box), leave ANTHROPIC_BASE_URL
# UNSET so claude talks to Anthropic directly — never force a localhost URL that
# isn't listening (that was the one hard break in the degrade path). env.sh may set
# PERSONAL_LITELLM_URL to a non-localhost target (e.g. a LAN tailscale IP); it's
# sourced after this file, so re-run the probe there if it overrides the URL.
PERSONAL_LITELLM_URL="${PERSONAL_LITELLM_URL:-http://localhost:4000}"
if command -v curl >/dev/null 2>&1 && \
   curl -sf -m 0.3 "$PERSONAL_LITELLM_URL/health/liveliness" >/dev/null 2>&1; then
  export ANTHROPIC_BASE_URL="$PERSONAL_LITELLM_URL"
else
  unset ANTHROPIC_BASE_URL
fi

# Model default is intentionally NOT set here — unset means claude uses its own
# current default, which is the right behavior for a fresh install. env.sh pins one.
