#!/usr/bin/env bash
# Launch claude with recent checkpoint context injected as the opening message.
# Reads checkpoint notes from $CHECKPOINT_DIR (or legacy $NOTES_DIR) for the current repo (past 3 days).
# Also registers this agent in the shared registry (~/.tmux/registry/) and
# injects agent communication tool instructions into the startup prompt.
# Falls back to plain `claude` if no notes found.
#
# Cross-platform (mac + Linux): the few OS-specific bits are guarded inline ($OSTYPE / a
# `[ -d ]` probe / BSD-or-GNU `date`+`stat` fallbacks), so this is the ONE shared copy —
# there is no per-OS override. env.defaults.sh (committed) then env.sh (per-machine,
# generated) are sourced first and supply machine paths + routing.

# Fleet install root. Self-default so this resolves for a spawned agent whose env
# was stripped (herdr pane); env.defaults.sh + substrate re-export the canonical value.
NEXUS_TMUX_DIR="${NEXUS_TMUX_DIR:-$HOME/.tmux}"
# Portable defaults FIRST (committed; works with no install.sh run — the degrade path),
# then the per-machine env.sh ON TOP (generated by install.sh; may be absent).
[ -f "$NEXUS_TMUX_DIR/env.defaults.sh" ] && source "$NEXUS_TMUX_DIR/env.defaults.sh"
[ -f "$NEXUS_TMUX_DIR/env.sh" ] && source "$NEXUS_TMUX_DIR/env.sh"

# Fleet env for agents that don't inherit a login shell (herdr panes; any spawn with a
# stripped env). Load the repo .env — DATABASE_URL (agent-memory MCP), bus config,
# tokens — so the agent AND its MCP servers get it. Read-and-export KEY=value (no shell
# eval of values; .env is written for node's loader), filling gaps only so we never
# override an already-set var (matches the slack-bridge .env loader semantics).
# env.sh normally sets AGENTS_NEXUS_DIR; the default is only a last resort and differs by
# OS layout (mac: ~/repos, Linux personal box: ~/repos).
case "$OSTYPE" in
  darwin*) _NEXUS_DEFAULT="$HOME/repos/agents-nexus" ;;
  *)       _NEXUS_DEFAULT="$HOME/repos/agents-nexus" ;;
esac
_ENV_FILE="${AGENTS_NEXUS_DIR:-$_NEXUS_DEFAULT}/.env"
if [ -f "$_ENV_FILE" ]; then
  while IFS='=' read -r _k _v; do
    case "$_k" in ''|\#*) continue ;; esac
    [ -z "${!_k:-}" ] && export "$_k=$_v"
  done < "$_ENV_FILE"
fi

# fnm (Linux) puts node/claude under a default-alias bin that a stripped popup PATH misses,
# so `exec claude` below would be "not found". Prepend it when present (self-guarded — the
# dir doesn't exist on mac/homebrew boxes, so this is a no-op there).
_FNM_BIN="$HOME/.local/share/fnm/aliases/default/bin"
[ -d "$_FNM_BIN" ] && case ":$PATH:" in *":$_FNM_BIN:"*) ;; *) export PATH="$_FNM_BIN:$PATH" ;; esac

# Claude Code self-updates in TWO stages: npm unpacks package.json + install.cjs, then
# install.cjs downloads the ~330MB platform binary into bin/claude.exe. Between those two
# steps the `claude` symlink sitting on PATH DANGLES — `command -v claude` prints nothing
# and exits 1 (indistinguishable from "not installed"), so the `exec claude` at the bottom
# of this script dies instantly and takes the pane with it BEFORE it can render anything.
# The user sees a keybind that "does nothing"; the error goes nowhere. Measured window:
# ~3m20s on 2026-08-19 (v2.1.235). An already-running agent survives it by holding the old
# inode open, which makes the fleet look half-broken rather than mid-update.
#
# The install self-heals, so wait it out rather than failing. Structural check only (no
# `claude --version` probe) — this runs on EVERY spawn and the happy path must stay free.
_claude_ready() {
  _cr_path="$(command -v claude 2>/dev/null)" || return 1
  [ -n "$_cr_path" ] && [ -x "$_cr_path" ]
}
if ! _claude_ready; then
  _cw_waited=0
  _cw_limit="${CLAUDE_WAIT_SECS:-300}"
  echo "open-claude: 'claude' not resolvable yet — likely a Claude Code self-update in flight; waiting up to ${_cw_limit}s" >&2
  while ! _claude_ready && [ "$_cw_waited" -lt "$_cw_limit" ]; do
    sleep 2
    _cw_waited=$((_cw_waited + 2))
    [ $((_cw_waited % 30)) -eq 0 ] && echo "open-claude: still waiting for 'claude' (${_cw_waited}s/${_cw_limit}s)" >&2
  done
  if _claude_ready; then
    echo "open-claude: 'claude' resolved after ${_cw_waited}s — continuing" >&2
  else
    # Hold the pane open. Exiting here would reproduce the exact silent-vanish this guards.
    echo "open-claude: FATAL — 'claude' still not executable after ${_cw_limit}s; not launching." >&2
    echo "  PATH=$PATH" >&2
    echo "  Check:  ls -la \"$_FNM_BIN/claude\"" >&2
    echo "  A dangling symlink there means an update died midway. Repair with:" >&2
    echo "    npm i -g @anthropic-ai/claude-code" >&2
    if [ -t 0 ]; then
      echo "  Press Enter to close this pane." >&2
      read -r _cw_ack || true
    else
      sleep 60
    fi
    exit 127
  fi
fi

# ANTHROPIC_BASE_URL is decided by the env layer (env.defaults.sh probes the local
# LiteLLM gateway and sets it only when reachable; env.sh may override). Do NOT force
# a localhost fallback here — on a box with no gateway that pointed every agent at a
# dead URL. Unset = talk to Anthropic directly, which is the correct degrade.

# Resolve checkpoint source — prefer CHECKPOINT_DIR (matches the writer skill);
# fall back to NOTES_DIR for back-compat with older env.sh installs.
CHECKPOINT_SRC="${CHECKPOINT_DIR:-${NOTES_DIR:-$HOME/vault/Checkpoints}}"
REPO_PATH="${PWD}"

# project_slug: the REPO's name, not the checkout directory's.
#
# These are the same for an ordinary clone and differ for a git worktree, whose
# directory is named <parent>_<repo>--<branch> — so a worktree agent registered
# as "flashback-fleet_management-dashboard--business-hours" instead of
# "management-dashboard".
#
# That is not just unpleasant to type on the bus. project_slug ALSO keys the
# agent-memory project, the checkpoint filenames and the prompt cache (see the
# uses below), so a worktree-spawned agent silently came up with none of its
# project's memory and wrote its checkpoints to a namespace nothing else reads.
# The bus name was the visible symptom; the lost continuity was the actual bug.
#
# git-common-dir resolves to the MAIN checkout's .git from inside a worktree and
# to the repo's own .git otherwise, so this returns exactly what basename used to
# for a normal clone — verified against both before changing it.
_slug_from_git() {
    local common main
    common=$(git -C "$REPO_PATH" rev-parse --path-format=absolute --git-common-dir 2>/dev/null) || return 1
    [ -n "$common" ] || return 1
    main=$(dirname "$common")
    [ -d "$main" ] || return 1
    basename "$main"
}

# A name already claimed by a LIVE agent must not be handed out twice: the bus
# resolves by name and takes the first match, so a duplicate would silently
# deliver another agent's messages here. Two worktrees of one repo hit this, and
# it is the case the long directory name was accidentally protecting against —
# so fall back to the directory name rather than collide.
_slug_is_taken() {
    local want="$1" f
    for f in "$HOME/.tmux/registry"/*; do
        [ -f "$f" ] || continue
        [ "$(basename "$f")" = "${TMUX_PANE:-${HERDR_PANE_ID:-}}" ] && continue
        [ "$(grep -m1 '^NAME=' "$f" 2>/dev/null | cut -d= -f2)" = "$want" ] && return 0
    done
    return 1
}

if [ -n "${PROJECT_SLUG:-}" ]; then
    project_slug="$PROJECT_SLUG"                      # explicit override always wins
else
    project_slug="$(basename "$REPO_PATH")"
    _git_slug="$(_slug_from_git || true)"
    if [ -n "$_git_slug" ] && [ "$_git_slug" != "$project_slug" ] && ! _slug_is_taken "$_git_slug"; then
        project_slug="$_git_slug"
    fi
fi

# ── Agent-memory Python (venv used by the MCP server) ──────────────────────
_AGENT_MEM_VENV="${AGENTS_NEXUS_DIR:-$HOME/repos/agents-nexus}/mnemon/.venv"
if [ -x "$_AGENT_MEM_VENV/bin/python3" ]; then
  MEMORY_PYTHON="$_AGENT_MEM_VENV/bin/python3"
elif [ -x "$_AGENT_MEM_VENV/Scripts/python3.exe" ]; then
  MEMORY_PYTHON="$_AGENT_MEM_VENV/Scripts/python3.exe"
else
  MEMORY_PYTHON="python3"
fi

# ── Register this agent in the shared registry ─────────────────────────────
# Files are keyed by pane ID (stable — unaffected by renumber-windows).
# tmux sets TMUX_PANE; herdr sets HERDR_PANE_ID — fold herdr's in so the agent
# registers (registry + name) in both substrates.
TMUX_PANE="${TMUX_PANE:-${HERDR_PANE_ID:-}}"
MY_PANE_ID="$TMUX_PANE"
MY_NAME="$project_slug"
# Workspace (bucket) label: set at spawn via NEXUS_WORKSPACE; else derive from the pane
# (herdr). Empty for flat/default agents, which resolve as unscoped (thin) names.
MY_WORKSPACE="${NEXUS_WORKSPACE:-}"
[ -z "$MY_WORKSPACE" ] && MY_WORKSPACE="$("$NEXUS_TMUX_DIR/substrate.sh" workspace-of "$MY_PANE_ID" 2>/dev/null || true)"

# This host's presence/FQDN label. SINGLE source = SLACK_PRESENCE_HOST — the SAME var the bridge's
# SELF_HOST (index.js) and agent-resolve.sh's nx_self_host() read — falling back to the short
# hostname. Injected into base context (Agent Communication, below) so an agent can tell whether a
# bus peer is same-host or remote: FQDN-style peer names are `<host>/…/<name>`, so a peer prefixed
# "$MY_HOST/" is on THIS box — hand files off by writing into its repo tree (no S3/user-drop detour).
MY_HOST="${SLACK_PRESENCE_HOST:-$(hostname -s 2>/dev/null || hostname 2>/dev/null || echo unknown)}"

# A2A sender identity — export the FULL FQDN component (workspace/name) so agent-send.sh
# stamps a `host/workspace/name` `from` WITHOUT depending on a live registry lookup. A bare
# name is ambiguous when the same name exists in >1 workspace (e.g. several `general`s), which
# makes a recipient misread a message as a self-loopback. The bridge adds the host (SELF_HOST).
# Honors an AGENT_FROM the launcher already set; empty workspace → bare name (flat/unscoped).
if [ -z "${AGENT_FROM:-}" ]; then
  if [ -n "$MY_WORKSPACE" ]; then export AGENT_FROM="$MY_WORKSPACE/$MY_NAME"; else export AGENT_FROM="$MY_NAME"; fi
fi

# Lock the window name so tmux doesn't override it with the process name
"$NEXUS_TMUX_DIR/substrate.sh" rename "$MY_PANE_ID" "$MY_NAME" 2>/dev/null

# The command post (overseer/orchestrator) is where you drive from — never an
# agent to reap. Tag it so the idle reaper protects it even if later renamed.
case "$MY_NAME" in
  overseer|orchestrator) "$NEXUS_TMUX_DIR/substrate.sh" tag-orchestrator "$MY_PANE_ID" 2>/dev/null ;;
esac

# ── Direct-auth carve-out: strip the gateway env for command-post panes ─────
# See NEXUS_DIRECT_AUTH_AGENTS in env.defaults.sh for the full why. Short form:
# Remote Control (/remote-control, /rc) refuses to register when an API key or
# auth token resolves, so a gateway-routed pane cannot be driven from a phone.
#
# Matched against BOTH the agent name and the workspace label, because a command
# post is usually named for its launch dir (e.g. `general`) and is identifiable
# only by NEXUS_WORKSPACE — matching on name alone would miss it, which is the
# same blind spot the tag-orchestrator case above still has.
#
# This must run AFTER env.sh (which re-forces ANTHROPIC_BASE_URL with a `:-`
# default) and BEFORE the /sess append below — hence here, not in the env layer.
# `unset` rather than reassignment is load-bearing: the gate tests for
# source==="none", and an empty-but-present var still resolves to a source.
_direct_auth=0
# shellcheck disable=SC2086  # deliberate word-split: the knob is a space-separated list
for _da in ${NEXUS_DIRECT_AUTH_AGENTS:-}; do
  if [ "$_da" = "$MY_NAME" ] || { [ -n "$MY_WORKSPACE" ] && [ "$_da" = "$MY_WORKSPACE" ]; }; then
    _direct_auth=1
    break
  fi
done
if [ "$_direct_auth" = "1" ]; then
  unset ANTHROPIC_BASE_URL ANTHROPIC_API_KEY ANTHROPIC_AUTH_TOKEN
  echo "open-claude: direct-auth pane (${MY_NAME}/${MY_WORKSPACE:-flat}) — gateway env stripped; /remote-control available, NO Langfuse trace for this session" >&2
fi
unset _da _direct_auth

# ── Tag LLM traffic so Langfuse names the trace after this window ───────────
# The proxy reads a `sess/<name>/` path prefix and uses it as the trace name +
# session id; without it every agent shows up as "claude-code". Slugify to a
# URL-path-safe segment (the proxy splits the prefix on the first "/").
if [ -n "${ANTHROPIC_BASE_URL:-}" ] && [ -n "$MY_NAME" ]; then
  _sess_slug=$(printf '%s' "$MY_NAME" | tr -c 'A-Za-z0-9._-' '-')
  export ANTHROPIC_BASE_URL="${ANTHROPIC_BASE_URL%/}/sess/${_sess_slug}"
fi

# Gate on the PANE only. `register` is keyed by pane and takes no slot, so the old
# `&& [ -n "$MY_SLOT" ]` gated registration on a window-index query (substrate
# pane-field) that RACES on herdr: at spawn time the daemon doesn't yet know a
# freshly-created pane, so pane-field returned empty → registration was silently
# skipped, leaving bridge-spawned agents unregistered (invisible to /agents, their
# permission prompts un-routed to Slack → wedged at the first prompt). MY_PANE_ID
# comes from HERDR_PANE_ID in the env (no daemon query), so it's reliably set.
if [ -n "$MY_PANE_ID" ]; then
  # Route through the shared `substrate register` verb (the one writer of the registry
  # format), so picker launches and seam-spawned agents register identically.
  "$NEXUS_TMUX_DIR/substrate.sh" register "$MY_PANE_ID" "$MY_NAME" "$REPO_PATH" "$MY_WORKSPACE"
  # Log session_start to memory buffer (best-effort — absent on a fleet-less install).
  [ -x "$NEXUS_TMUX_DIR/memory-hook.py" ] && "$NEXUS_TMUX_DIR/memory-hook.py" session_start "$MY_PANE_ID" "$REPO_PATH" &
fi

# ── Recent checkpoint notes ────────────────────────────────────────────────
# Gated by NEXUS_INJECT_CHECKPOINTS (0 = omit); lookback by NEXUS_CHECKPOINT_DAYS;
# total size capped by NEXUS_CHECKPOINT_MAX_KB (0 = unlimited). See env.defaults.sh.
context=""
if [ "${NEXUS_INJECT_CHECKPOINTS:-1}" = "1" ] && [ "${NEXUS_CONTEXT_MODE:-full}" != "pointer" ]; then
  _ckpt_days="${NEXUS_CHECKPOINT_DAYS:-3}"
  # BSD date (Mac): -v-Nd; GNU date (Linux): -d 'N days ago'
  cutoff=$(date -v-"${_ckpt_days}"d +%Y-%m-%d 2>/dev/null || date -d "${_ckpt_days} days ago" +%Y-%m-%d)
  # Collect matching checkpoint files within the window, sorted oldest→newest
  while IFS= read -r f; do
    date_part=$(basename "$f" | cut -c1-10)
    if [[ "$date_part" > "$cutoff" || "$date_part" = "$cutoff" ]]; then
      context+="$(cat "$f")"$'\n\n'
    fi
  done < <(ls -1 "$CHECKPOINT_SRC"/*-${project_slug}-checkpoint.md 2>/dev/null | sort)
  # Optional size cap — keep the NEWEST bytes (files are oldest→newest, so the
  # freshest checkpoint is at the tail and matters most). 0 disables the cap.
  _ckpt_max_kb="${NEXUS_CHECKPOINT_MAX_KB:-0}"
  if [ "$_ckpt_max_kb" -gt 0 ] 2>/dev/null; then
    _ckpt_max_bytes=$(( _ckpt_max_kb * 1024 ))
    if [ "${#context}" -gt "$_ckpt_max_bytes" ]; then
      context="[older checkpoint context trimmed to ${_ckpt_max_kb}KB via NEXUS_CHECKPOINT_MAX_KB]"$'\n\n'"${context: -$_ckpt_max_bytes}"
    fi
  fi
fi

# ── Auto-cache recovery (previous session context) ───────────────────────
CACHE_FILE="$NEXUS_TMUX_DIR/cache/${project_slug}.md"
cache_section=""
if [ "${NEXUS_INJECT_CACHE:-1}" = "1" ] && [ -f "$CACHE_FILE" ]; then
  # Capture each stat arm into its own assignment. A `||` chain INSIDE $( ) keeps the
  # stdout of the FAILING arm too: on Linux `stat -f` is --file-system, so it prints a
  # whole filesystem block, exits non-zero, and the GNU arm's epoch gets appended to it.
  # The result is a fatal arithmetic syntax error that exits the shell at this line.
  cache_mtime=$(stat -c %Y "$CACHE_FILE" 2>/dev/null) || cache_mtime=$(stat -f %m "$CACHE_FILE" 2>/dev/null) || cache_mtime=0
  cache_age=$(( $(date +%s) - ${cache_mtime:-0} ))
  if [ "$cache_age" -lt 86400 ]; then
    cache_section=$(cat "$CACHE_FILE")
    mv "$CACHE_FILE" "${CACHE_FILE%.md}.used" 2>/dev/null
  else
    rm -f "$CACHE_FILE"
  fi
fi

# ── Agent communication tools ─────────────────────────────────────────────
REGISTRY_SCRIPT="$NEXUS_TMUX_DIR/agent-registry.sh"
SEND_SCRIPT="$NEXUS_TMUX_DIR/agent-send.sh"
# Is the agent bus live? Probe the local bridge's health (cheap, <1s) so we document
# the bus as the DEFAULT transport only when it can actually deliver. `--via-bus`
# force-routes through the bridge regardless of the agent's NEXUS_BUS_ENABLED, so the
# bridge's own bus state — not an env var — is the right signal. No bridge / bus off ->
# fall back to the local-only guidance.
bus_on=0
if command -v curl >/dev/null 2>&1; then
  case "$(curl -s --max-time 1 "http://127.0.0.1:${NEXUS_BUS_PORT:-${SLACK_BRIDGE_PORT:-8788}}/health" 2>/dev/null)" in
    *'"bus":true'*) bus_on=1 ;;
  esac
fi
registry_section=""
if [ "${NEXUS_INJECT_REGISTRY:-1}" = "1" ] && [ "${NEXUS_CONTEXT_MODE:-full}" != "pointer" ] && [ -x "$REGISTRY_SCRIPT" ]; then
  peers_output=$("$REGISTRY_SCRIPT" peers --exclude "$MY_PANE_ID" 2>/dev/null || true)
  if [ "$bus_on" = "1" ]; then
    comms_body="**To message another agent, DEFAULT to the NATS agent bus.** Post once and the orchestrator delivers it idle-gated, buffered, and durable (JetStream holds it if the recipient's bridge is down), across hosts:
  - \`$SEND_SCRIPT <host>/<workspace>/<name> <message>\` — deliver to that agent when it next goes idle

**Address agents by FQDN.** The registry is a NATS JetStream KV bucket keyed \`<host>.<workspace>.<name>\`; you type the same identity slash-separated. You are \`${MY_HOST}/<your-workspace>/${MY_NAME}\`. A bare name still resolves, but it is ambiguous the moment two agents share it — which is normal in a fleet — so qualify it.

Discovery (read-only — find who to address, then message them over the bus):
  - \`curl -s localhost:${NEXUS_BUS_PORT:-${SLACK_BRIDGE_PORT:-8788}}/agents\` — the live fleet from the KV; each entry carries a ready-to-paste \`fqdn\`
  - \`$REGISTRY_SCRIPT peers --exclude ${MY_PANE_ID}\` — THIS host's agents only (slot, name, directory)
  - \`$REGISTRY_SCRIPT whoami --exclude ${MY_PANE_ID}\` — show your own slot, name, and directory

The transport is NATS. Slack carries only the human notify/reply leg — no agent-to-agent traffic. \`--via-slack\` survives as a deprecated alias of \`--via-bus\`; despite the name it forces the NATS bus.

Fallback — direct local send (same-host only; NOT durable or auditable and can be missed). Prefer the bus; only use this for a local/ephemeral ping, and say that you did:
  - \`$SEND_SCRIPT --local <slot_or_name> <message>\` — inject straight into a same-host agent's pane
  - \`$REGISTRY_SCRIPT broadcast --exclude ${MY_PANE_ID} <message>\` — send to ALL other agents at once"
  else
    comms_body="To message another agent:
  - \`$REGISTRY_SCRIPT peers --exclude ${MY_PANE_ID}\` — list all active agents
  - \`$SEND_SCRIPT <slot_or_name> <message>\` — send a message to a specific agent
  - \`$REGISTRY_SCRIPT broadcast --exclude ${MY_PANE_ID} <message>\` — send to ALL other agents
  - \`$REGISTRY_SCRIPT whoami --exclude ${MY_PANE_ID}\` — show your own slot, name, and directory"
  fi
  registry_section="## Agent Communication
You are agent **${MY_NAME}** on host **${MY_HOST}**. You are part of a multi-agent system; peers may be on THIS host or remote. Peer names are often FQDN-style \`<host>/…/<name>\`: a peer whose name is prefixed \`${MY_HOST}/\` is on the SAME box as you — hand files to it directly by writing into its repo tree under \`~/repos\` (e.g. \`.../docs/incoming\`), NO S3/user-drop detour; only a cross-host handoff needs a transfer mechanism. (Messaging still goes over the bus either way.) ALWAYS pass --exclude ${MY_PANE_ID} to avoid listing yourself.

${comms_body}

### Current Peers
\`\`\`
${peers_output}
\`\`\`
Re-run peers before messaging to get up-to-date slot numbers; prefer name-based addressing over slot numbers."
fi

# ── Query prior knowledge from memory store ────────────────────────────────
memory_section=""
if [ "${NEXUS_INJECT_MEMORY:-1}" = "1" ] && [ "${NEXUS_CONTEXT_MODE:-full}" != "pointer" ] && [ -x "$NEXUS_TMUX_DIR/memory-recall.py" ]; then
  memory_section=$("$MEMORY_PYTHON" "$NEXUS_TMUX_DIR/memory-recall.py" "$project_slug" --max-tokens "${NEXUS_MEMORY_MAX_TOKENS:-2000}" 2>/dev/null || true)
fi

# ── Pointer mode: a lean "load context on demand" note replacing the eager dump ─
# In pointer mode the checkpoint + memory + peers blocks above are skipped entirely
# (no filesystem/DB/registry reads at spawn). Instead the agent gets a short pointer
# telling it HOW to pull each on demand when a task actually needs it. Gated by the
# same INJECT flags so turning a block off also removes its pointer line.
pointer_section=""
if [ "${NEXUS_CONTEXT_MODE:-full}" = "pointer" ]; then
  _pl=""
  if [ "${NEXUS_INJECT_CHECKPOINTS:-1}" = "1" ]; then
    _pl="${_pl}- Recent checkpoints: read the newest \`${CHECKPOINT_SRC}/*-${project_slug}-checkpoint.md\` files (or run your checkpoint skill) for what recent sessions did."$'\n'
  fi
  if [ "${NEXUS_INJECT_MEMORY:-1}" = "1" ]; then
    _pl="${_pl}- Prior knowledge: query the agent-memory MCP (\`search_similar\`/\`query_notes\`, project \`${project_slug}\`) before non-trivial work."$'\n'
  fi
  if [ "${NEXUS_INJECT_REGISTRY:-1}" = "1" ] && [ -x "$REGISTRY_SCRIPT" ]; then
    _pl="${_pl}- Peers / messaging: you are agent **${MY_NAME}** on **${MY_HOST}** in a multi-agent system. Get the live fleet from the NATS presence KV with \`curl -s localhost:${NEXUS_BUS_PORT:-${SLACK_BRIDGE_PORT:-8788}}/agents\` (each entry carries a ready-to-paste \`fqdn\`; \`$REGISTRY_SCRIPT peers --exclude ${MY_PANE_ID}\` lists THIS host only), then message by FQDN with \`$SEND_SCRIPT <host>/<workspace>/<name> <message>\` (NATS bus; durable, cross-host). Add \`--local\` for a same-host pane injection."$'\n'
  fi
  if [ -n "$_pl" ]; then
    pointer_section="## Context (load on demand)
This spawn is lean — recent checkpoints, prior-knowledge notes, and the peer roster were NOT pasted in. Pull only what a task needs:
${_pl}"
  fi
fi

# ── Orchestrator seed / restore (seeded and restored agents) ───────────────
# SEED_PROMPT        — a task to begin on immediately (e.g. the request that
#                      triggered the spawn). Becomes the FIRST section of the opening
#                      prompt; the usual checkpoint/memory/registry context follows
#                      for awareness. Delivered as the launch prompt — never via
#                      send-keys — so there is no terminal-readiness race.
# RESTORE_CHECKPOINT — path to a specific checkpoint file to resume from (a reaped
#                      agent's last checkpoint). Injected as restore context when
#                      readable; logs + falls back to a plain spawn when missing.
# Both are unset for normal launches, so default behavior is unchanged.
seed_section="${SEED_PROMPT:-}"
restore_section=""
if [ -n "${RESTORE_CHECKPOINT:-}" ]; then
  if [ -r "$RESTORE_CHECKPOINT" ]; then
    restore_section="$(cat "$RESTORE_CHECKPOINT")"
  else
    echo "open-claude: RESTORE_CHECKPOINT not readable ($RESTORE_CHECKPOINT) — restoring without it" >&2
  fi
fi

# ── Build claude args ──────────────────────────────────────────────────────
claude_args=()
# CLAUDE_EXTRA_ARGS - verbatim extra flags, word-split on purpose.
#
# For genuinely unattended spawns. CLAUDE_PERMISSION_MODE alone cannot get there,
# because EVERY posture has its own first-run dialog and a spawned pane sits on
# whichever one it hits with nobody to answer:
#   manual            -> "Do you want to proceed?" at the first tool call
#   bypassPermissions -> "you accept all responsibility" consent, persisted
#                        nowhere in ~/.claude.json, so it returns every session
#   auto              -> "Set up auto mode for your environment?" onboarding
# `claude --dangerously-skip-permissions` is the one that comes up running, and
# it is a FLAG not a mode, so it needs a passthrough. Observed on real panes.
#
# Unquoted expansion is deliberate: flags, not paths with spaces. Unset for every
# normal launch, so default behaviour is unchanged.
# shellcheck disable=SC2206
[ -n "${CLAUDE_EXTRA_ARGS:-}" ] && claude_args+=(${CLAUDE_EXTRA_ARGS})
[ -n "$MY_NAME" ]       && claude_args+=(--name "$MY_NAME")
[ -n "$CLAUDE_MODEL" ]  && claude_args+=(--model "$CLAUDE_MODEL")
[ -n "$CLAUDE_EFFORT" ] && claude_args+=(--effort "$CLAUDE_EFFORT")
# Permission posture (opt-in): default|acceptEdits|bypassPermissions|plan. Unset →
# claude's own default (interactive; the read-only auto-approve classifier still gates
# prompts and escalates mutations to the human notify leg). Set at spawn for a hands-off background
# agent — e.g. CLAUDE_PERMISSION_MODE=bypassPermissions for a fire-and-forget reviewer,
# which mirrors the Conductor SDK runner's permission_mode="bypassPermissions". Normal
# launches leave it unset and are unchanged. NOTE: acceptEdits only auto-accepts file
# edits, not Bash/MCP calls, so it does NOT make a tool-driven agent (e.g. one posting
# MR comments via glab) hands-off — use bypassPermissions for that.
[ -n "$CLAUDE_PERMISSION_MODE" ] && claude_args+=(--permission-mode "$CLAUDE_PERMISSION_MODE")

# ── Pre-accept workspace trust for this launch dir ─────────────────────────
# Claude Code gates a per-directory trust dialog on
#   ~/.claude.json → projects["<dir>"].hasTrustDialogAccepted
# There is no global "trust all" switch, and a trusted parent does not reliably
# cascade, so every untrusted dir — including each fresh git worktree — prompts
# on launch. Seed the flag for THIS dir just before exec so the dialog never
# fires. flock guards concurrent fleet launches racing on the shared JSON.
seed_trust() {
  command -v jq >/dev/null 2>&1 || return 0
  local cfg="$HOME/.claude.json" tmp
  { [ -f "$cfg" ] && jq -e . "$cfg" >/dev/null 2>&1; } || return 0
  tmp="$(mktemp "${TMPDIR:-/tmp}/claude-trust.XXXXXX")" || return 0
  if jq --arg d "$REPO_PATH" '(.projects[$d].hasTrustDialogAccepted) = true' "$cfg" >"$tmp" 2>/dev/null && [ -s "$tmp" ]; then
    mv "$tmp" "$cfg"
  else
    rm -f "$tmp"
  fi
}
if command -v flock >/dev/null 2>&1; then
  ( flock 200; seed_trust ) 200>"$HOME/.claude.json.lock"
else
  seed_trust
fi

# ── Reporting conventions (always injected; NEXUS_INJECT_CONVENTIONS=0 to omit) ──
# Added 2026-09-07: one UNTAGGED orchestrator claim, wrong, reached three agents before
# anyone re-derived it — a write on it would have changed a report already delivered.
# The tag is one word and stops that at the first hop.
# A per-box brief wins over the inline block: an overlay symlinks its own file to
# ~/.tmux/conventions.md (the personal authorization below is wrong for a regulated box).
NEXUS_CONVENTIONS_FILE="${NEXUS_CONVENTIONS_FILE:-$HOME/.tmux/conventions.md}"
conventions_section=""
conventions_source="inline"
if [ "${NEXUS_INJECT_CONVENTIONS:-1}" = "1" ] && [ -r "$NEXUS_CONVENTIONS_FILE" ]; then
  conventions_section="$(cat "$NEXUS_CONVENTIONS_FILE")"
  conventions_source="$NEXUS_CONVENTIONS_FILE"
elif [ "${NEXUS_INJECT_CONVENTIONS:-1}" = "1" ]; then
  conventions_section='## Authorization (standing policy — Alex, 2026-09-07)

**You may do anything reversible. Default to acting, not asking.** Branch, commit, push,
open PRs, refactor, add tests, edit docs and cards. You do not need permission for any of
it. Alex is risk-tolerant and would rather you shipped and were wrong than sat idle waiting
for a reply — especially overnight, when a blocked agent wastes the whole window.

**If a thing can be undone with a revert, a down-migration, or a re-run, it is in budget.**
Prod is locked down, but dev is fair game.

**The short list that is NOT reversible.** Everything here is evidenced, not hypothetical:

1. **Merging or deleting data.**
2. **Deleting or overwriting untracked files.** There is no git history to restore from.
   Move to `~/vault/Archive/<name>-<date>/` with a README instead of deleting — and
   `git clean -fd`, `git reset --hard` and `checkout -f` in a shared checkout need a
   peer'"'"'s reply first, not just an announcement.
3. **A write that changes a report someone has already received.**
4. **Printing a secret.** It cannot be un-printed; the remediation is rotation. See the
   credential rules in CLAUDE.md.

**Everything else: go.** If you are unsure whether something is on that list, it almost
certainly is not — ask yourself what the undo command is, and if you can name one, run it.

**There is no escalation path overnight. Nobody is awake between 11PM and 8AM Mountain time
and no notification will reach anyone.** So when you hit one of the four, do NOT stop and
file a card. **Do everything up to the irreversible step and leave it one command away:**
write the migration, stage the branch, build the exact list, capture the before-state, and
put the precise apply command AND its revert command in your report. The goal is that the
human does thirty seconds of work in the morning, not thirty minutes of reconstruction. A
blocked overnight agent that produced a ready-to-run change is useful; one that produced a
question is not.

## Shared working trees — you may not be alone in your checkout

Several repos here have MULTIPLE agents in one working tree, which means **one HEAD and one
working directory between you**. Git will not tell you.

**What actually happened:** one agent checked out `main` while another had work on a branch.
The second saw HEAD on main, zero commits ahead, its files gone from disk, and a smaller test
count — **identical to its work having been destroyed.** Nothing was lost, but only because
the work was already committed.

- **Commit early, to an explicitly named branch (no slashes in branch name).** Necessary,
  and *not sufficient*.
- **Always use an explicit pathspec.** A bare `git commit` sweeps whatever a peer left staged.
  That happened, and cost a `reset --soft` to undo. Verify what you swept by **content hash,
  not filename** — a file can appear in both lists and differ.
- **Re-read `git status` immediately before any branch operation.** What you saw a minute ago
  has moved.
- **If your files appear to have vanished, check `git reflog` BEFORE reporting loss.** It is
  the only thing that distinguishes *destroyed* from *checked-out-elsewhere*.
- **Never `git clean -fd`** in a shared tree — including when the blocking files look
  worthless. The natural fix for *"untracked working tree files would be overwritten by
  merge"* is exactly that command; remove blockers **by explicit path** instead.

**⛔ A NEGATIVE CONTROL NEVER GOES IN A SHARED TREE.** If you are deliberately breaking
something to prove a check can fail — a broken test, a malformed file, a planted secret — do
it in `git worktree add` or a temp clone, **never** by checking it into the shared tree, even
briefly. For the two minutes it is there, any peer running the suite sees a red result that is
not theirs and has no way to know it is yours. This is the rule that branch hygiene does not
cover: committed, well-named branches still hand a peer a broken working directory just for
being present. Deliberate damage needs isolation even more than accidental damage does.

## Reporting conventions (fleet-wide)

**Tag every factual claim with how you know it.** Whenever you state something another
agent or the orchestrator might act on:

- `VERIFIED <file:line>` / `VERIFIED <command>` — you checked it yourself, this session
- `RELAYED` — you are passing on someone else'"'"'s claim, unchecked
- `ASSUMED` — plausible, reasoned from, not checked

**An untagged claim will be read as VERIFIED.** If you did not check it, say so — including
when the claim came from the orchestrator. "My orchestrator told me" is RELAYED, not
VERIFIED, and relaying it untagged is how one wrong claim reaches three agents at once.

**Before acting irreversibly on a RELAYED claim, re-derive it.** Cheaply, once. Applies to
migrations, merges, deletes, prod config, and anything a human can see.

**Derivable values: derive them, never record them.** A commit count, a row count, a file
list — quote the COMMAND, not the number. A recorded derivable is a fact with an expiry date
that nothing announces. If a number must appear, stamp it as a measurement with a time.

**Say what would have made you wrong.** A green check that cannot fail carries no information.
If you report a passing test, a clean sweep, or "no instances found", state what a failure
would have looked like and confirm that outcome was actually reachable.

**Provenance applies to REVIEWS, not just reports — this is where it fails in practice.**
Observed on this fleet: one reviewer named its method ("confirmed via search that X is
defined once") — legibly VERIFIED. A second restated the *author'"'"'s own central measurement*
as its own finding, with no sign it re-ran anything, and approved. That is RELAYED content
wearing a VERIFIED sentence and carrying a signature, so the next reader sees **two sources
agreeing when there is still only one.**

**The reviewer is where a bad number should die. Untagged, it is where the number gets
laundered.** So: tag your review claims, re-run what you repeat, and when auditing a review
panel, grep the review bodies for the author'"'"'s own figures — **a verbatim echo is the tell.**

**Every PR body carries a `VERIFY:` line.** One line, naming a measurement that would come
out DIFFERENT if your change did not work.

It must be something someone else can run. `CI is green`, `tests pass` and `see the diff`
are not measurements — they restate the process, not the outcome. A verifier agent reads
these after merge and reports CONFIRMED, DRIFTED, or UNFALSIFIABLE.

**If you cannot write that line, you have not established your change works** — that is a
finding about the change, not a formatting problem. Say so in the PR rather than inventing
a claim.'
fi

# ── Guard: prove the conventions block survived its own quoting ────────────
# The block above is ONE single-quoted string. An unescaped apostrophe in the
# prose closes it mid-statement, and the assignment then becomes a PREFIX
# assignment on whatever word follows -- so conventions_section ends up EMPTY
# rather than truncated, and the prose up to the next apostrophe EXECUTES as
# shell commands.
#
# An ODD number of stray apostrophes fails loudly at spawn. An EVEN number
# passes `bash -n` and every other syntax check, which is exactly how two of
# them shipped through three commits and silently removed the entire standing
# brief from every spawned agent for three days before anyone noticed.
#
# Escape apostrophes inside the block the way the rest of it does. To launch
# deliberately without a brief, set NEXUS_INJECT_CONVENTIONS=0 -- do not
# delete this check.
CONVENTIONS_MIN_BYTES="${CONVENTIONS_MIN_BYTES:-2000}"
if [ "${NEXUS_INJECT_CONVENTIONS:-1}" = "1" ] && [ "${#conventions_section}" -lt "$CONVENTIONS_MIN_BYTES" ]; then
  printf '%s\n' \
    "open-claude: FATAL - conventions_section is ${#conventions_section} bytes, floor is ${CONVENTIONS_MIN_BYTES} (source: ${conventions_source})." \
    "  Inline block: broken quoting, almost certainly an unescaped apostrophe. File: empty or truncated." \
    "  Agents would otherwise launch with no standing brief and nothing would say so." \
    "  Fix the quoting, or set NEXUS_INJECT_CONVENTIONS=0 to launch without one." >&2
  exit 1
fi

# ── Review partner (set NEXUS_REVIEW_PARTNER=<fqdn> at spawn) ──────────────
# Added 2026-09-07: overnight, every highest-value finding came from agents reviewing
# each other, and all of it was ACCIDENTAL overlap. Pairing formalises that in PARALLEL —
# one central reviewer is a serial bottleneck and lacks the domain context that catches.
pairing_section=""
if [ -n "${NEXUS_REVIEW_PARTNER:-}" ]; then
  pairing_section="## Your review partner: \`${NEXUS_REVIEW_PARTNER}\`

Message them with \`$SEND_SCRIPT ${NEXUS_REVIEW_PARTNER} <one-line message>\`.

**Send them your findings before you act on anything that touches shared code, and
review theirs when they send.** You are not asking permission — the standing
authorization above still applies and you should keep moving. You are getting a second
pair of eyes from someone with overlapping context, which is the thing that has caught
the most real defects in this fleet.

**What a useful review is, based on what actually worked:**

- **Check the claim, not the conclusion.** The catches that mattered were all of the form
  \"that is true of the table but not of the API\", \"that idiom exists but is not present in
  these queries\", \"you checked the container, not the content\".
- **Say which parts you did NOT check.** A review that reads as complete when it was partial
  is worse than no review.
- **Disagree in the open.** Do not soften a correction to be collegial. Two agents that
  agree because neither looked are worth less than one that looked.
- **\"Your usage is correct\" is a claim like any other** — if a peer tells you your code is
  fine, verify it yourself before relying on it. That exact sentence preceded the discovery
  of a live 74-row leak on this fleet.

**PROVISIONAL — this mechanism is under evaluation.** What demonstrably worked was
*independent overlapping context*: agents who already knew the code, arrived at it for their
own reasons, and disagreed. An ASSIGNED partner is not automatically that, and a dutiful
low-context review is the exact failure a single central reviewer would produce. So:

**If you do not have real context on what your partner sent, say so and do not approve.**
"I lack the context to check this" is a useful review. A nod is not. Naming the parts you
could not judge is what keeps a second signature from becoming a second rubber stamp.

Reviewing costs you a few minutes and is the highest-yield thing you will do today."
fi

# ── Launch claude with assembled context ───────────────────────────────────
if [ -n "$seed_section" ] || [ -n "$restore_section" ] || [ -n "$cache_section" ] || [ -n "$context" ] || [ -n "$registry_section" ] || [ -n "$memory_section" ] || [ -n "$pointer_section" ] || [ -n "$conventions_section" ] || [ -n "$pairing_section" ]; then
  prompt=""
  # Seed first: it is the actual task this agent was launched to do.
  if [ -n "$seed_section" ]; then
    prompt="You have been launched by the Nexus orchestrator to work on the following request. Agent-to-agent messaging is the NATS bus described under Agent Communication below; there is no Slack path. Begin working on it; the context below is for situational awareness:"$'\n\n'"${seed_section}"
  fi
  if [ -n "$restore_section" ]; then
    [ -n "$prompt" ] && prompt="${prompt}"$'\n\n'
    prompt="${prompt}You are being restored after a previous session was checkpointed and closed (reaped while idle). Here is your last checkpoint — resume where you left off:"$'\n\n'"${restore_section}"
  fi
  if [ -n "$cache_section" ]; then
    [ -n "$prompt" ] && prompt="${prompt}"$'\n\n'
    prompt="${prompt}Your previous session was interrupted. Here is the working context from that session — use it to pick up where you left off:"$'\n\n'"${cache_section}"
  fi
  if [ -n "$context" ]; then
    [ -n "$prompt" ] && prompt="${prompt}"$'\n\n'
    prompt="${prompt}Here are recent checkpoint notes for this project (past 3 days). Please review them to get up to speed before we begin:"$'\n\n'"${context}"
  fi
  if [ -n "$memory_section" ]; then
    [ -n "$prompt" ] && prompt="${prompt}"$'\n\n'
    prompt="${prompt}${memory_section}"
  fi
  if [ -n "$pointer_section" ]; then
    [ -n "$prompt" ] && prompt="${prompt}"$'\n\n'
    prompt="${prompt}${pointer_section}"
  fi
  if [ -n "$registry_section" ]; then
    [ -n "$prompt" ] && prompt="${prompt}"$'\n\n'
    prompt="${prompt}${registry_section}"
  fi
  if [ -n "$pairing_section" ]; then
    [ -n "$prompt" ] && prompt="${prompt}"$'\n\n'
    prompt="${prompt}${pairing_section}"
  fi
  # Conventions last: they govern how everything above gets reported back, and the
  # closing position is the one an agent re-reads when composing a report.
  if [ -n "$conventions_section" ]; then
    [ -n "$prompt" ] && prompt="${prompt}"$'\n\n'
    prompt="${prompt}${conventions_section}"
  fi
  if [ "${NEXUS_PROMPT_DRY_RUN:-0}" = "1" ]; then printf '%s\n' "$prompt"; exit 0; fi
  exec claude "${claude_args[@]}" "$prompt"
else
  [ "${NEXUS_PROMPT_DRY_RUN:-0}" = "1" ] && exit 0
  exec claude "${claude_args[@]}"
fi
